import {initNav}         from './modules/nav.js';
import {initLoader}      from './modules/loader.js';
import {initScroll}      from './modules/scroll.js';
import {initCounters}    from './modules/counters.js';
import {initLightbox}    from './modules/lightbox.js';
import {initForm}        from './modules/form.js';
import {initTransitions} from './modules/transitions.js';
import {initAnchorScroll}from './modules/anchor-scroll.js';
import {initMasonry}     from './modules/masonry.js';
import {initMagnetic}    from './modules/magnetic.js';

initLoader();
initNav();
initMasonry();
initScroll();
initCounters();
initLightbox();
initForm();
initTransitions();
initAnchorScroll();
initMagnetic();
